"""create analyses table

Revision ID: 0001
Revises:
Create Date: 2026-10-09 10:03:04.880698
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('input_mode', sa.String(length=16), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_outcome', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('outcome_definition', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.CheckConstraint("input_mode IN ('file', 'manual')", name='input_mode_valid'),
    sa.CheckConstraint("predicted_outcome IN ('success', 'failure')", name='predicted_outcome_valid'),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name='probability_range'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
